### ISSUE TITLE
Existing TODOs (missing core functionality)

### ISSUE THREAD

**Issue by swopet** [swopet/WavyBoi#1]
# Todos

- [ ] Make Audio Handler much more robust to runtime errors, dynamic finding of audio device, etc.
- [ ] Make Audio Handler dynamically update the max volume (i.e. if the user increases/decreases their system volume)
- [ ] Make Audio Handler update rate customizable
- [ ] Add thread-safe audio file loading, audio file processing
- [ ] Add Hotkey assignment customization to objects
- [ ] Create New Object Staging Area
- [ ] Create Clipboard class
- [ ] Make display screen customizable in UI
- [ ] Implement WBScene default param reset routine
- [ ] Add WBScene examples with interesting animations
- [ ] Add Function to WBScene that exposes expected parameters to the user
- [ ] Add Compilation documentation
- [ ] Create .wbstate file format
- [ ] Create .wbstate Save() and Load() functions
- [ ] Add Unit and integration testing
- [ ] Make the UI not look like garbo and feel a little more responsive
- - [ ] Make input/output buttons light up when you hover over them
- - [ ] Make names of inputs light up when you hover over them
- - [ ] Add little menus for all objects
- - [ ] Switch UI to IMGUI?
- [ ] Make custom allocator for plugin memory that assigns memory to plugins, so if there is a memory leak in a plugin the main thread can kill all plugins and continue gracefully
- [ ] Add support for generic plugins / plugin libraries (that don't just output images)
- [ ] Add MIDI objects
- [x] Make sure all Objects have position at their top-left corner (keep it consistent)
- [x] Add Texture Register objects for fancy feedback loops
- [x] Expose size and position of available displays to user
- [x] Add image sequence importer
- [x] Create Commandline Area, add commandline controls
- [x] Create Audio Handler control module
- [x] Make workspace size agnostic of window size
- [x] Add pause/play functionality to Video
- [x] Make control window respond dynamically to resizing
- [x] Make sure all Objects implement Click, drag, select, delete routines
- [x] Make SceneObject wait in separate thread for completion of sceneload
